### ISSUE TITLE
page.waitFor() in line 56 of index.js is a deprecated function.

### ISSUE THREAD

**Issue by CoderCowMoo** [tascord/compass-edu#7]
**To Reproduce**
Steps to reproduce the behavior. E.g:
1. Go to 'Line 56' with Visual Studio Code.
2. Let it tell you that it has deprecated.

I got it to work using this function.
await new Promise(r => setTimeout(r, 3000));

Thanks.

**Comment by heheleo** [comment]
Please use the updated method `waitForTimeout` instead of that, even though it is basically the same :)

**Comment by CoderCowMoo** [comment]
Ok thanks
